const { match } = require('ffp-js')
const moment = require('moment')

const weather2text = match
  .case(id => id === 200)(_ => ({ main: "천둥번개", description: "가벼운 비에 천둥번개가 칩니다."}))
  .case(id => id === 201)(_ => ({ main: "천둥번개", description: "비와 천둥번개가 칩니다."}))
  .case(id => id === 202)(_ => ({ main: "천둥번개", description: "많은 비에 천둥번개가 칩니다."}))
  .case(id => id === 210)(_ => ({ main: "천둥번개", description: "약한 천둥번개가 칩니다."}))
  .case(id => id === 211)(_ => ({ main: "천둥번개", description: "천둥번개가 칩니다."}))
  .case(id => id === 212)(_ => ({ main: "천둥번개", description: "강한 천둥번개가 칩니다."}))
  .case(id => id === 221)(_ => ({ main: "천둥번개", description: "가끔씩 천둥번개가 칩니다."}))
  .case(id => id === 230)(_ => ({ main: "천둥번개", description: "약한 보슬비와 천둥번개가 칩니다."}))
  .case(id => id === 231)(_ => ({ main: "천둥번개", description: "보슬비와 천둥번개가 칩니다."}))
  .case(id => id === 232)(_ => ({ main: "천둥번개", description: "강한 비와 천둥번개가 칩니다."}))
  .case(id => id === 300)(_ => ({ main: "보슬비", description: "보슬보슬 비가 내립니다."}))
  .case(id => id === 301)(_ => ({ main: "보슬비", description: "보슬보슬 비가 내립니다."}))
  .case(id => id === 302)(_ => ({ main: "보슬비", description: "강한 보슬비가 내립니다."}))
  .case(id => id === 310)(_ => ({ main: "보슬비", description: "약한 보슬비가 내립니다."}))
  .case(id => id === 311)(_ => ({ main: "보슬비", description: "비가 뿌려집니다."}))
  .case(id => id === 312)(_ => ({ main: "보슬비", description: "강한 비가 뿌려집니다."}))
  .case(id => id === 313)(_ => ({ main: "보슬비", description: "강한 비가 뿌려집니다."}))
  .case(id => id === 314)(_ => ({ main: "보슬비", description: "강한 비가 뿌려집니다."}))
  .case(id => id === 321)(_ => ({ main: "보슬비", description: "강한 비가 뿌려집니다."}))
  .case(id => id === 500)(_ => ({ main: "비", description: "비가 내립니다."}))
  .case(id => id === 501)(_ => ({ main: "비", description: "비가 내립니다."}))
  .case(id => id === 502)(_ => ({ main: "비", description: "비가 내립니다."}))
  .case(id => id === 503)(_ => ({ main: "비", description: "비가 내립니다."}))
  .case(id => id === 504)(_ => ({ main: "비", description: "비가 내립니다."}))
  .case(id => id === 511)(_ => ({ main: "비", description: "비가 내립니다."}))
  .case(id => id === 520)(_ => ({ main: "비", description: "비가 내립니다."}))
  .case(id => id === 521)(_ => ({ main: "비", description: "비가 내립니다."}))
  .case(id => id === 522)(_ => ({ main: "비", description: "비가 내립니다."}))
  .case(id => id === 531)(_ => ({ main: "비", description: "비가 내립니다."}))
  .case(id => id === 600)(_ => ({ main: "눈", description: "눈이 내립니다."}))
  .case(id => id === 601)(_ => ({ main: "눈", description: "눈이 내립니다."}))
  .case(id => id === 602)(_ => ({ main: "눈", description: "눈이 내립니다."}))
  .case(id => id === 611)(_ => ({ main: "눈", description: "눈이 내립니다."}))
  .case(id => id === 612)(_ => ({ main: "눈", description: "눈이 내립니다."}))
  .case(id => id === 613)(_ => ({ main: "눈", description: "눈이 내립니다."}))
  .case(id => id === 615)(_ => ({ main: "눈", description: "눈이 내립니다."}))
  .case(id => id === 616)(_ => ({ main: "눈", description: "눈이 내립니다."}))
  .case(id => id === 620)(_ => ({ main: "눈", description: "눈이 내립니다."}))
  .case(id => id === 621)(_ => ({ main: "눈", description: "눈이 내립니다."}))
  .case(id => id === 622)(_ => ({ main: "눈", description: "눈이 내립니다."}))
  .case(id => id === 701)(_ => ({ main: "안개", description: "안개가 꼈습니다."}))
  .case(id => id === 711)(_ => ({ main: "안개", description: "안개가 꼈습니다."}))
  .case(id => id === 721)(_ => ({ main: "실안개", description: "실안개가 낍니다."}))
  .case(id => id === 731)(_ => ({ main: "실안개", description: "실안개가 낍니다."}))
  .case(id => id === 741)(_ => ({ main: "실안개", description: "실안개가 낍니다."}))
  .case(id => id === 751)(_ => ({ main: "실안개", description: "실안개가 낍니다."}))
  .case(id => id === 761)(_ => ({ main: "실안개", description: "실안개가 낍니다."}))
  .case(id => id === 762)(_ => ({ main: "실안개", description: "실안개가 낍니다."}))
  .case(id => id === 771)(_ => ({ main: "돌풍", description: "돌풍이 붑니다."}))
  .case(id => id === 781)(_ => ({ main: "돌풍", description: "돌풍이 붑니다."}))
  .case(id => id === 800)(_ => ({ main: "맑음", description: "맑은 날씨입니다."}))
  .case(id => id === 801)(_ => ({ main: "구름", description: "구름이 조금 끼었습니다."}))
  .case(id => id === 802)(_ => ({ main: "구름", description: "구름이 조금 끼었습니다."}))
  .case(id => id === 803)(_ => ({ main: "구름", description: "구름이 끼었습니다."}))
  .case(id => id === 804)(_ => ({ main: "구름", description: "구름이 많이 끼었습니다."}))
  .else(_ => ({ main: '날씨', description: '설명'}))

const getDate = (date, format) => moment(date).get(format)

module.exports = {
  getDate,
  weather2text
}
